---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/cms/pages
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - page
- type: document
  path: src/cms/menu.json
  label: Menu
upload_dir: public/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
